extremism_car_rental_homepage:
    path:     /
    defaults: { _controller: ExtremismCarRentalBundle:Default:index }
extremism_car_rental_cars:
    resource: "@ExtremismCarRentalBundle/Controller"
    type: annotation
    prefix: /