<?php

namespace Extremism\CarRentalBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CarOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarOrderRepository extends EntityRepository
{
    public function getOrderAndCar($orderId)
    {
        $qp = $this->createQueryBuilder('carOrder')
            ->leftJoin('carOrder.cars', 'cars')
            ->select('carOrder', 'cars')
            ->where('carOrder.id = :orderId')
                ->setParameter('orderId', $orderId)
            ;
        return $qp->getQuery()->getOneOrNullResult();
    }
}
