<?php

namespace Extremism\CarRentalBundle\Repository;

/**
 * CarOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
