<?php

namespace Extremism\CarRentalBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFreeCars()
    {
        $qb = $this->createQueryBuilder('cars')
            ->select('cars')
        ;
        $qb->where(
            $qb->expr()->orX(
                $qb->expr()->lt('cars.endReservationAt', new \DateTime()),
                $qb->expr()->eq('cars.endReservationAt', null)
            ))
            ->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->lt('cars.endRentAt', new \DateTime()),
                    $qb->expr()->eq('cars.endRentAt', null)
                ));
//        $qb->expr()->orX(
//            $qb->expr()->lt('cars.endReservationAt', new \DateTime()),
//            $qb->expr()->eq('cars.endReservationAt', null)
//        );
//        $qb->expr()->orX(
//            $qb->expr()->lt('cars.endRentAt', new \DateTime()),
//            $qb->expr()->eq('cars.endRentAt', null)
//        );

        return $qb->getQuery()->getArrayResult();
    }
}
